/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131318",
        "surface-dim": "#131318",
        "surface-bright": "#39383e",
        "surface-container-lowest": "#0e0e13",
        "surface-container-low": "#1b1b20",
        "surface-container": "#1f1f25",
        "surface-container-high": "#2a292f",
        "surface-container-highest": "#35343a",
        "on-surface": "#e4e1e9",
        "on-surface-variant": "#ccc3d8",
        "inverse-surface": "#e4e1e9",
        "inverse-on-surface": "#303036",
        "outline": "#958da1",
        "outline-variant": "#4a4455",
        "surface-tint": "#d2bbff",
        "primary": "#d2bbff",
        "on-primary": "#3f008e",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#732ee4",
        "secondary": "#4cd7f6",
        "on-secondary": "#003640",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#905b00",
        "on-tertiary-container": "#ffe1c0",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "background": "#131318",
        "on-background": "#e4e1e9",
        "surface-variant": "#35343a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "max-width": "1440px",
        "unit": "8px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono"],
        "display-lg-mobile": ["Outfit"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "headline-md": ["Outfit"],
        "display-lg": ["Outfit"]
      }
    },
  },
  plugins: [],
}
